### ISSUE TITLE
Release cycle for rhyslbw/cardano-graphql-hasura

### ISSUE THREAD

**Issue by ksemaev** [input-output-hk/cardano-graphql#192]
The compose file mentions `rhyslbw/cardano-graphql-hasura:v1.0.0-rc.11` which located not in `inputoutput` dockerhub account https://github.com/input-output-hk/cardano-graphql/blob/master/docker-compose.yml#L46

**docker-entrypoint.sh** in that that image `rhyslbw/cardano-graphql-hasura:v1.0.0-rc.11` (https://hub.docker.com/r/rhyslbw/cardano-graphql-hasura) varies a lot from script mentioned in docker-compose.build in repo https://github.com/input-output-hk/cardano-graphql/blob/master/hasura/docker-entrypoint.sh

The tags on the image itself are created daily, and there's no transparency into what commit/branch triggers the build. Can you please create a tagging policy for images attached to github tags are or at least realeses?

**Comment by rhyslbw** [comment]
The tagging process can be seen in the [Jenkinsfile](https://github.com/input-output-hk/cardano-graphql/blob/master/Jenkinsfile#L42-L86). The only difference with `cardano-graphql-hasura` is the dockerhub scope, but that will move over to `inputoutput` soon. I suggest using the [latest release](https://github.com/input-output-hk/cardano-graphql/releases) rather than `master`

**Comment by rhyslbw** [comment]
The `inputoutput` org now has the repo, and the most recent release has been pushed.  
https://hub.docker.com/repository/docker/inputoutput/cardano-graphql-hasura
