### ISSUE TITLE
Restarting db-sync removes Postgres views used by cardano-graphql

### ISSUE THREAD

**Issue by jaydp17** [input-output-hk/cardano-graphql#205]
I'm running cardano-db-sync v2.0.0 with `EXTENDED=true` and `v1.0.0-rc.12` of cardano-graphql.

**How to reproduce the problem:**
1. start cardano-db-sync
2. start cardano-graphql
3. Everything works well, till here ✅
4. restart cardano-db-sync

**Actual result:**
Restarting cardano-db-sync removes all Postgres views used by cardano-graphql

**Expected Result:**
Do not break cardano-graphql.
If removal of views is necessary, maybe there's some workaround we can use to not bread cardano-graphql?

Thanks in advance for the help!!

**Comment by rhyslbw** [comment]
@jaydp17 I've transferred your issue here as it's just a gap in the documentation, although it is demonstrated in code. Here's some info to help before that changes:

> If removal of views is necessary, maybe there's some workaround we can use to not break cardano-graphql?

The strategy used by `cardano-db-sync` is shadowed here, using the `hasura-cli` as demonstrated in [pre-start.sh](https://github.com/input-output-hk/cardano-graphql/blob/master/packages/api-cardano-db-hasura/hasura/pre-start.sh). It's used within the [Hasura Dockerfile](https://github.com/input-output-hk/cardano-graphql/blob/master/packages/api-cardano-db-hasura/hasura/Dockerfile), but needs to be included in a deployment definition outside of this. The only caveat at this point is if `cardano-db-sync` restarts, you should also restart the current `cardano-graphql-hasura` service. There's an effort in progress to decouple the GraphQL server from the non-outward facing service restart requirements, so I'll leave this issue open until that is complete.
