### ISSUE TITLE
activeStake_aggregate missing

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-graphql#345]
I've noticed that you've merged in the "ActiveStake" feature and it seems to work great. I've noticed though that activeStake_aggregate doesn't seem to be fully implemented yet. It's runnable from the Hasura API / interface but it hasn't been fully plugged in yet to the GraphQL API. 

I just wanted to let you know in case it was forgotten about.

Cheers!

**Comment by rhyslbw** [comment]
Thanks @CyberCyclone 
It was an explicit decision at the time to anchor the query to the `Epoch` model given the record is _active stake in an epoch_. Since you're prompt I can see value in the top-level query too, so I've implemented this with an example of the utility outside the scope on an epoch.
