### ISSUE TITLE
About metadata server /metadata/healthcheck endpoint

### ISSUE THREAD

**Issue by bgiegel** [input-output-hk/cardano-graphql#608]
Hello ! I’m trying to setup a full cardano node on kubernetes and I have some issues with the cardano-graphql part. My node is in sync, my db-sync also. But when I launch the cardano-graphql it stay stuck at the Metadata client step.

{"name":"cardano-graphql","hostname":"tg-ada-0","pid":1,"level":30,"module":"MetadataFetchClient","msg":"Initializing","time":"2021-09-25T06:26:28.931Z","v":0}

From what I can see in the code and from the debug logs is that this part is trying to call the metadata healthcheck endpoint.
I have setup `https://tokens.cardano.org/` as the base URL. When I try to access the health endpoint at `https://tokens.cardano.org/metadata/healthcheck` I’m getting an "Requested subject 'healthcheck' not found" error.

I tried to look at the offchain-metadata-tools repo if there is any info on the healthcheck endpoint but didn’t find any.

What am I doing wrong here ? Is it the right base URL ? Is it possible that this endpoint does not exist anymore or that the location has changed ?

Thanks in advance for the help.

**Comment by bgiegel** [comment]
okay so the /metadata/healthcheck is still failing :

`curl https://tokens.cardano.org/metadata/healthcheck
Requested subject 'healthcheck' not found`

but this morning the graphql was up... Without me doing anything special... I’m still curious to know the answer about the healtcheck retry though, if anybody knows something about this.

**Comment by rhyslbw** [comment]
Hi @bgiegel 

The logic to determine the availability of the metadata service is a workaround since there's no formal endpoint. A 404 response is the expected outcome to determine a healthy service, which I should have left a inline comment to confirm this intent.

https://github.com/input-output-hk/cardano-graphql/blob/7c4e92ea62f8dbbbbb9a698c24b825479a844bbe/packages/api-cardano-db-hasura/src/MetadataClient.ts#L23-L33

Hopefully we can improve this in the future.

**Comment by bgiegel** [comment]
Oh ! ok so I was looking at the wrong thing and something else was retrying. Thx for the answer :)
