### ISSUE TITLE
GraphQL Playground works only while db-sync container is stopped

### ISSUE THREAD

**Issue by miracatici** [input-output-hk/cardano-graphql#644]
I made fresh install with recent snapshot. After 28-30 hours later, I realized that cardano-db-sync-extended container keeps restarting again and again. It reports `Error: validateGenesisDistribution: Expected initial block to have 14505 but got 0`. In addition playground is not working. When I stopped cardano-db-sync-extended container and restart graphql, playground start serving. I made test queries, `{ cardano { tip { number slotNo epoch { number } } } }` and `{ cardanoDbMeta { initialized syncPercentage }}` it returns logical responses.

Is there anything wrong? Does GraphQL container depends db-sync?

**Comment by CyberCyclone** [comment]
I use that error message as a sign that everything has finished imported and you need to bring the whole stack down and bring it back up. Since they depend on each other, you need to bring all of them down. When you bring it back up, it will take about 15 - 30 minutes to start up (depending on IOPS). It will then most likely rollback to the start of the most recent epoch that the db-sync has. Since the rewards are kept in memory, it needs to go back to the start of the epoch to re-calulate them.

After some time (depending on how far back your snapshot was), it can take some time syncing up to the network Tip. It could take an hour, maybe more.
