### ISSUE TITLE
Graphql 7.0.0 for the Cardano testnet

### ISSUE THREAD

**Issue by fmira21** [input-output-hk/cardano-graphql#755]
### Ask a question

Hi guys!
I am going to update my Testnet node, but cannot find the v.7.0.0-testnet image. What image can I use for the Testnet setup?

Thank you in advance!

**Comment by rhyslbw** [comment]
We're no longer building _testnet_ images since the network is being deprecated, however, if you cannot switch to one of the new testnets, _preview_ or _preprod_, you can override the config at runtime by mounting [this dir](https://github.com/input-output-hk/cardano-configurations/tree/303f3a3035c52eb753b533d53ef439c6b4cde9c9/network/testnet) to `/config`.
